import Project from "../models/Project";

import humanoiaPreview from "../assets/screenshots/humanoia-preview.webp";
import humanoia1 from "../assets/screenshots/humanoia-1.webp";
import humanoia2 from "../assets/screenshots/humanoia-2.webp";
import humanoia3 from "../assets/screenshots/humanoia-3.webp";
import formulafacil1 from "../assets/screenshots/formulafacil.webp";
import formulafacilUtn from "../assets/screenshots/formulafacil-utn.webp";
import formulafacilClassic from "../assets/screenshots/formulafacil-classic.webp";
import formulafacilPractice from "../assets/screenshots/formulafacil-practice.webp";
import reservationWorkflow from "../assets/screenshots/reservation-workflow.webp";
import reservationIntermedia from "../assets/screenshots/reservation-intermedia.webp";
import reservationBitrix from "../assets/screenshots/reservation-bitrix.webp";

export class ProjectRepository {
  private projects: Project[] = [];

  constructor() {
    this.initializeProjects();
  }

  private initializeProjects(): void {
    const humanoiaProject = new Project(
      "HumanoIA",
      "https://humanoia.neocities.org",
      {
        es: "Juego para adivinar cuál cara es real y cuál fue generada por IA.",
        en: "Game to guess which face is real and which one is AI-generated."
      },
      {
        es: "HumanoIA es un proyecto interactivo que desafía la percepción humana en la era de la inteligencia artificial. Los usuarios se enfrentan a pares de imágenes faciales donde deben identificar cuál es una fotografía real y cuál ha sido generada por algoritmos de IA.",
        en: "HumanoIA is an interactive project that challenges human perception in the age of artificial intelligence. Users face pairs of facial images where they must identify which is a real photograph and which has been generated by AI algorithms."
      },
      "HTML • CSS • JavaScript",
      humanoiaPreview,
      [humanoia1, humanoia2, humanoia3],
      {
        es: ["Interfaz intuitiva y responsive", "Sistema de puntuación en tiempo real", "Diferentes niveles de dificultad"],
        en: ["Intuitive and responsive interface", "Real-time scoring system", "Different difficulty levels"]
      },
      {
        es: ["Optimización de imágenes para carga rápida", "Creación de algoritmo de selección balanceado"],
        en: ["Image optimization for fast loading", "Creation of balanced selection algorithm"]
      },
      "Frontend",
      "from-purple-500 to-pink-500",
      "🎮",
      "https://github.com/Isaacxiddd/HumanoIA"
    );

    const formulaFacilProject = new Project(
      "Formula Fácil UTN",
      "https://formulafacilutn.neocities.org",
      {
        es: "Herramienta educativa para estudiantes de la UTN con más de 3.000 usuarios. Memorización de fórmulas matemáticas mediante gamificación y práctica activa.",
        en: "Educational tool for UTN students with over 3,000 users. Mathematical formula memorization through gamification and active practice."
      },
      {
        es: "Herramienta educativa interactiva creada para estudiantes de la UTN que ayuda a memorizar fórmulas matemáticas mediante técnicas de gamificación y práctica activa.\n\nLa plataforma alcanzó más de 3.000 usuarios y fue utilizada por estudiantes para reforzar contenidos de Análisis Matemático y Geometría, combinando aprendizaje visual, ejercicios interactivos y seguimiento del progreso.\n\nDesarrollada íntegramente con HTML, CSS y JavaScript, incorpora renderizado matemático con MathJax, gráficos SVG dinámicos y un sistema de puntuación y rachas en tiempo real para mejorar la retención de conceptos.",
        en: "Interactive educational tool created for UTN students that helps memorize mathematical formulas through gamification techniques and active practice.\n\nThe platform reached over 3,000 users and was used by students to reinforce content from Mathematical Analysis and Geometry, combining visual learning, interactive exercises and progress tracking.\n\nBuilt entirely with HTML, CSS and JavaScript, it incorporates mathematical rendering with MathJax, dynamic SVG graphics and a real-time scoring and streak system to improve concept retention."
      },
      "HTML5 • CSS3 • JavaScript • MathJax • SVG",
      formulafacil1,
      [formulafacilUtn, formulafacilClassic, formulafacilPractice],
      {
        es: [
          "+3.000 usuarios alcanzados en 2026",
          "5 módulos temáticos: Funciones, Inecuaciones, Geometría, Valor Absoluto, Intervalos",
          "Dos modos de juego: Classic y Practice con niveles de dificultad",
          "Sistema de gamificación con puntos, rachas y efectos de sonido",
          "Galería completa de figuras y guía de fórmulas detallada",
          "Diseño responsive optimizado para celular y escritorio"
        ],
        en: [
          "+3,000 users reached in 2026",
          "5 thematic modules: Functions, Inequalities, Geometry, Absolute Value, Intervals",
          "Two game modes: Classic and Practice with difficulty levels",
          "Gamification system with points, streaks and sound effects",
          "Complete figure gallery and detailed formula guide",
          "Responsive design optimized for mobile and desktop"
        ]
      },
      {
        es: [
          "Implementación de renderizado de fórmulas matemáticas con MathJax",
          "Creación de gráficos vectoriales SVG dinámicamente",
          "Optimización del sistema de puntuación y rachas en tiempo real",
          "Diseño de interfaz intuitiva con feedback visual inmediato"
        ],
        en: [
          "Implementation of mathematical formula rendering with MathJax",
          "Dynamic creation of SVG vector graphics",
          "Optimization of real-time scoring and streak system",
          "Design of intuitive interface with immediate visual feedback"
        ]
      },
      "Frontend",
      "from-teal-600 to-blue-600",
      "🎮",
      "https://github.com/Isaacxiddd/FormulafacilUTN"
    );

    const reservationProject = new Project(
      "Automatización de Reservas",
      "https://github.com/Isaacxiddd/Reservation-automation",
      {
        es: "Sistema de automatización que conecta reservas de Airbnb/Booking con el CRM Bitrix24 usando n8n.",
        en: "Automation system that connects Airbnb/Booking reservations with Bitrix24 CRM using n8n."
      },
      {
        es: "Sistema de automatización que procesa correos de confirmación de Airbnb y Booking.com vía IMAP, clasifica el tipo de evento (nueva reserva, cancelación, mensaje, reseña), extrae los datos del huésped y la propiedad, y los registra automáticamente como deals en Bitrix24. Incluye validación anti-duplicados con PostgreSQL/Supabase y lógica de fallback: si no encuentra la propiedad, crea el deal igual y genera una tarea manual para intervención.",
        en: "Automation system that processes Airbnb and Booking.com confirmation emails via IMAP, classifies event types (new booking, cancellation, message, review), extracts guest and property data, and automatically registers them as deals in Bitrix24. Includes anti-duplication validation with PostgreSQL/Supabase and fallback logic: if the property isn't found, it still creates the deal and generates a manual task for intervention."
      },
      "n8n • Bitrix24 API • PostgreSQL • Supabase • JavaScript • IMAP",
      reservationWorkflow,
      [reservationWorkflow, reservationIntermedia, reservationBitrix],
      {
        es: [
          "Lectura de emails de confirmación vía IMAP (Airbnb y Booking)",
          "Clasificación automática del tipo de evento",
          "Extracción de datos: huésped, propiedad, fechas, código de confirmación",
          "Creación automática de deals en Bitrix24 con tareas vinculadas",
          "Validación anti-duplicados con base de datos PostgreSQL/Supabase",
          "Fallback resiliente: crea el deal aunque falle el matching de propiedad"
        ],
        en: [
          "Confirmation email reading via IMAP (Airbnb and Booking)",
          "Automatic classification of event type",
          "Data extraction: guest, property, dates, confirmation code",
          "Automatic deal creation in Bitrix24 with linked tasks",
          "Anti-duplication validation with PostgreSQL/Supabase database",
          "Resilient fallback: creates the deal even if property matching fails"
        ]
      },
      {
        es: [
          "Diseño de lógica de fallback para evitar pérdida de reservas ante fallas de matching",
          "Implementación de índice anti-duplicados persistente en Supabase",
          "Parsing robusto de emails con múltiples formatos de Airbnb y Booking"
        ],
        en: [
          "Fallback logic design to avoid losing reservations on matching failures",
          "Implementation of persistent anti-duplication index in Supabase",
          "Robust email parsing handling multiple formats from Airbnb and Booking"
        ]
      },
      "Automatización",
      "from-orange-500 to-amber-600",
      "⚡"
    );

    this.projects.push(formulaFacilProject, reservationProject, humanoiaProject);
  }

  getAllProjects(): Project[] {
    return [...this.projects];
  }

  getProjectByName(name: string): Project | undefined {
    return this.projects.find(project => project.name === name);
  }
}
